name = "medium"
compatibility_date = "2023-12-01"

 [vars]
 DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNzE3OGVmZDUtY2RjNy00N2JkLTgxZGUtY2FiMjIyYmQ1MTU4IiwidGVuYW50X2lkIjoiYjgxZGE4YzVkNmJjNWM4OTJmMGVkY2FmNTRmYTNlZTUxMzQyODlmYWZmZmYyYmQ3MDRhZDQ3MTIwNWU0YTI2NCIsImludGVybmFsX3NlY3JldCI6ImFhZTA0ODgzLWFjNTAtNDkyMi1iMDg1LWFlOTdmNDcxOGUzZSJ9.cnew44hGbNVupoOfCYbrD840gKkypsEvlhLoUFKyFPs"
 JWT_KEY="Mayanksecret"
 BCRYPT_SALT_ROUNDS = 10

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"